yt-dlp: short filename to fix `File name too long` error
```
04/23 08:03:47 [ERROR] CUID#7 - Download aborted. URI=https://rr2---sn-2op5q5-58.googlevideo.com/videoplayback?expire=1776953026&ei=YtLpab2zBfO7kucPqJPUiA4&ip=20.161.30.53&id=o-AMuKbPO8rKfGgupMl4Yp5qJMErWmuy5bA-uwM9HwMPf-&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1776931426%2C&mh=wN&mm=31%2C26&mn=sn-2op5q5-58%2Csn-5uaeznze&ms=au%2Conr&mv=m&mvi=2&pl=16&rms=au%2Cau&initcwndbps=3063750&siu=1&bui=AUUZDGKJQeQl9JM7O-9fiiv9wWGnHe8CpV2VWrwa_KB6wXs7n6r07h7IddJt_YMKhicK_1Z6oQ&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=rSXITs0UexywXDG68Qzz4RoU&rqh=1&gir=yes&clen=64370495&dur=5195.141&lmt=1731122677963501&mt=1776931029&fvip=5&keepalive=yes&lmw=1&fexp=51565116%2C51565681%2C51869322&c=TVHTML5&sefc=1&txp=5532434&n=r9MeMSYo7nnRWw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AHEqNM4wRgIhAMmgA22b85i0sg6_DEa9XY3PlRdnZCf3hQ692EGc6HJ7AiEA8fF-53fdRAJNv9ejEPICZPimHtOLB_wLCS_ASz6aN_o%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgNV9TlqOBtTfZj_COlZGMN71zvohzZU42L-KjEBqF0HMCIQCTmbbKKFk4-Q0O49I5ibqJRFAR2j_vke5tzgC0YAaA6g%3D%3D
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://rr2---sn-2op5q5-58.googlevideo.com/videoplayback?expire=1776953026&ei=YtLpab2zBfO7kucPqJPUiA4&ip=20.161.30.53&id=o-AMuKbPO8rKfGgupMl4Yp5qJMErWmuy5bA-uwM9HwMPf-&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1776931426%2C&mh=wN&mm=31%2C26&mn=sn-2op5q5-58%2Csn-5uaeznze&ms=au%2Conr&mv=m&mvi=2&pl=16&rms=au%2Cau&initcwndbps=3063750&siu=1&bui=AUUZDGKJQeQl9JM7O-9fiiv9wWGnHe8CpV2VWrwa_KB6wXs7n6r07h7IddJt_YMKhicK_1Z6oQ&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=rSXITs0UexywXDG68Qzz4RoU&rqh=1&gir=yes&clen=64370495&dur=5195.141&lmt=1731122677963501&mt=1776931029&fvip=5&keepalive=yes&lmw=1&fexp=51565116%2C51565681%2C51869322&c=TVHTML5&sefc=1&txp=5532434&n=r9MeMSYo7nnRWw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AHEqNM4wRgIhAMmgA22b85i0sg6_DEa9XY3PlRdnZCf3hQ692EGc6HJ7AiEA8fF-53fdRAJNv9ejEPICZPimHtOLB_wLCS_ASz6aN_o%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgNV9TlqOBtTfZj_COlZGMN71zvohzZU42L-KjEBqF0HMCIQCTmbbKKFk4-Q0O49I5ibqJRFAR2j_vke5tzgC0YAaA6g%3D%3D
  -> [RequestGroup.cc:761] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:221] errNum=36 errorCode=16 Failed to open the file /home/runner/work/gha-playground/gha-playground/./金剛經論壇，覺培法師主持，心保和尚、覺誠法師、慧祥法師共同探討，金剛經最核心價值？金剛經如何運用於生活？深入金剛經，實現無住生心自在生活。佛光山金光明寺，國際佛光會中華總會，影片人間佛教讀書會總部提供 [XQadgREbD74].f251.webm.part, cause: File name too long

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR: aria2c exited with code 16
```